### ISSUE TITLE
ID and rest_name in post_json

### ISSUE THREAD

**Issue by pjg250** [RockefellerArchiveCenter/boxafeller#4]
```
  // Give name and ID to device
  rest.set_id("001");
  rest.set_name("Carty McCartface");
```

I'm not sure whether you wanted "Carty McCartface" in the code available on github. I'm not sure whether we're still using this name or not.

**Comment by helrond** [comment]
Yeah it's really just something to identify the Arduino in the REST JSON, so I think I'll leave it as is. Thanks!
